name: essenmelia_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.6.1
  # riverpod_annotation: ^2.6.1

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # UI & Routing
  go_router: ^14.8.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  
  # Utilities
  intl: 0.20.2
  uuid: ^4.3.3
  share_plus: ^9.0.0
  file_picker: ^6.0.0

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  flutter_localizations:
    sdk: flutter
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  # riverpod_generator: ^2.6.3
  
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
