name: essenmelia_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  # riverpod_annotation: ^2.6.1

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # UI & Routing
  go_router: ^14.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  
  # Utilities
  intl: 0.20.2
  uuid: ^4.3.3
  share_plus: ^10.0.0
  file_picker: ^8.0.0

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  flutter_localizations:
    sdk: flutter
  web: ^1.1.1
  fl_chart: ^1.1.1
  photo_view: ^0.15.0
  http: ^1.6.0
  url_launcher: ^6.3.2
  google_mlkit_text_recognition: ^0.15.1
  google_mlkit_object_detection: ^0.15.1
  image_cropper: ^11.0.0
  quick_settings: ^1.0.1
  image: ^4.7.2
  pasteboard: ^0.3.0
  desktop_drop: ^0.7.0
  dotted_border: ^2.1.0
  path: ^1.9.1
  dynamic_color: ^1.8.1
  archive: ^4.0.7
  flutter_js: ^0.8.4
  yaml: ^3.1.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  device_calendar: ^4.3.3
  flutter_markdown: ^0.7.7+1
  crypto: ^3.0.7
  animations: ^2.1.1
  # receive_intent: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  # riverpod_generator: ^2.6.3
  
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/Essenmelia.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/Essenmelia.png"
  # Use the same PNG for monochrome to let the tool generate the resource structure
  # Then we will manually replace it with the correct Vector Drawable XML
  monochrome_android: "assets/images/Essenmelia.png"
  min_sdk_android: 21

flutter:
  assets:
    - assets/images/
    - assets/extensions/com.essenmelia.api_tester/
    - assets/extensions/com.essenmelia.event_test/
    - assets/extensions/com.essenmelia.kitchen_sink/
    - assets/extensions/system.external_call/
    - assets/docs/
  generate: true
  uses-material-design: true
